\hypertarget{classFoo__exception}{}\section{Foo\+\_\+exception Class Reference}
\label{classFoo__exception}\index{Foo\+\_\+exception@{Foo\+\_\+exception}}


Exception for concurrent\+\_\+container.  




{\ttfamily \#include $<$test\+\_\+container\+\_\+move\+\_\+support.\+h$>$}

Inheritance diagram for Foo\+\_\+exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classFoo__exception}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hypertarget{classFoo__exception_a4d045e133205e0a8d4f78d61bfe03cb0}{}virtual const char $\ast$ {\bfseries what} () const   throw ()\label{classFoo__exception_a4d045e133205e0a8d4f78d61bfe03cb0}

\end{DoxyCompactItemize}


\subsection{Detailed Description}
Exception for concurrent\+\_\+container. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/\+Users/pourya/\+Desktop/platform/repos/tetcutter/src/3rdparty/tbb/src/test/test\+\_\+container\+\_\+move\+\_\+support.\+h\end{DoxyCompactItemize}
